### PR TITLE
Fix for XCode 13 issue relating to "unavailable api..."

### LINKED ISSUE #150: Build errors with Xcode 13 Beta 3
With the latest beta of Xcode 13, while building sampleViewer, we get this following error with the toolkit `Extensions.swift`  and `MeasureToolbar.swift` files

`'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`

2021-07-20 at 3 51 PM

### PR DESCRIPTION
**Pull request by mhdostal**
The resolves #150 by moving the `topViewController()` method the `UIApplication` extension to `MeasureToolbar`.  That was the only place that was using it.  This fix preserves the existing `MeasureToolbar` api.  It does require `MeasureToolbar` to be marked `@available(iOSApplicationExtension, unavailable)`.

Tested on Xcode 13 Beta 4 and Xcode 12.5.

### CODE REVIEW

**Review by saratchandrakarumuri — APPROVED** [review]
Tested with Xcode 13 beta and iOS 15 and able to build application with no errors

File: Sources/ArcGISToolkit/MeasureToolbar.swift [hunk 1]
```diff
@@ -689,4 +688,19 @@ extension MeasureToolbar: UnitsViewControllerDelegate {
             fatalError("Unsupported unit type")
         }
     }
+    
+    func topViewController(_ controller: UIViewController? = UIApplication.shared.windows.first(where: { $0.isKeyWindow })?.rootViewController) -> UIViewController? {
```
Comment (philium) [inline Sources/ArcGISToolkit/MeasureToolbar.swift:692]: Methinks this should be private.

```suggestion
    private func topViewController(_ controller: UIViewController? = UIApplication.shared.windows.first(where: { $0.isKeyWindow })?.rootViewController) -> UIViewController? {
```

**Review by philium — APPROVED** [review]
